#!/bin/sh

# make sure sphere-client starts first
sv start /home/ninja/service/sphere-client || exit 1

cd /opt/ninjablocks/sphere-go-homecloud
exec /opt/ninjablocks/sphere-go-homecloud/sphere-go-homecloud
